name: cacti
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - aom=3.5.0
  - async-timeout=5.0.1
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - cuda-cudart=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.1.105
  - cuda-runtime=12.1.0
  - cuda-version=12.1
  - datasets=3.2.0
  - dill=0.3.8
  - ffmpeg=5.1.2
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - h2=4.1.0
  - hpack=4.1.0
  - huggingface_hub=0.27.1
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=19.0.0
  - libarrow-acero=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcurl=8.11.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libopus=1.3.1
  - libparquet=19.0.0
  - libpciaccess=0.18
  - libpng=1.6.46
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsentencepiece=0.2.0
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.21.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4
  - nlohmann_json=3.11.3
  - nltk=3.9.1
  - numpy==1.23.5
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.4.0
  - orc=2.0.3
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=9.4.0
  - pip=25.0
  - prometheus-cpp=1.3.0
  - propcache=0.2.1
  - pthread-stubs=0.4
  - pyarrow=19.0.0
  - pyarrow-core=19.0.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - s2n=1.5.11
  - safetensors=0.5.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - sentence-transformers=2.7.0
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - timm=1.0.9
  - tk=8.6.13
  - tokenizers=0.19.1
  - torchtriton=2.2.0
  - torchvision=0.17.2
  - tqdm=4.67.1
  - transformers=4.42.4
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yarl=1.18.3
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
